#include QMK_KEYBOARD_CONFIG_H

#undef LEADER_TIMEOUT
#define LEADER_TIMEOUT 300
#undef ONESHOT_TAP_TOGGLE
#define ONESHOT_TAP_TOGGLE 2
#undef ONESHOT_TIMEOUT
#define ONESHOT_TIMEOUT 2000

#define NO_DEBUG
#undef NO_PRINT
#define USER_PRINT

#undef TAPPING_TERM
#define TAPPING_TERM 150
#define PERMISSIVE_HOLD
#define RETRO_TAPPING
